import "@/styles/globals.css";
import ThemeRegistry from "./themeRegistry";
import AnimatedFooter from "@/components/animations/AnimatedFooter";
import SmoothScroll from "@/components/animations/SmoothScroll";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  other: {
    'grammarly': 'false',
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <SmoothScroll />
          <div style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}>
            <main style={{ flex: 1 }}>{children}</main>
            <AnimatedFooter />
          </div>
        </ThemeRegistry>
      </body>
    </html>
  );
}
